# docker compose up -d redis mongodb mysql postgres rabbitmq elasticsearch kibana
version: '3.9'
services:
  postgres:
    container_name: postgres_container1
    image: postgres
    environment:
      - POSTGRES_USER=joblance
      - POSTGRES_PASSWORD=joblance
      - POSTGRES_DB=joblance_reviews
    ports:
      - '5432:5432'
    volumes:
      - ./docker-volumes/postgres:/var/lib/postgresql

  rabbitmq:
    container_name: rabbitmq_container1
    image: rabbitmq:3.13-rc-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=joblance
      - RABBITMQ_DEFAULT_PASS=joblance
    ports:
      # AMQP protocol port
      - '5672:5672'
      # Management UI
      - '15672:15672'

networks:
  elastic:
    name: elastic
